### ISSUE TITLE
Reactjs: Uncaught TypeError: arweave__WEBPACK_IMPORTED_MODULE_1__.init is not a function

### ISSUE THREAD

**Issue by fewwwww** [decentldotland/weave-aggregator#1]
Using the sample code of 

```
import { getWeaveAggregator } from "weave-aggregator"

async function podcasts() {
  const podcastsMetadata = await getWeaveAggregator("permacast");

  return podcastsMetadata
}
```
throwing me this error message: 
<img width="725" alt="截屏2022-01-11 下午8 34 54" src="https://user-images.githubusercontent.com/41555918/149048295-c6fb0907-0332-44a9-8794-67b417ffd50b.png">

I am using weave-aggregator in React set up by create-react-app, with package.json looks like this: 
```
{
  "name": "permajpg",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.1",
    "@testing-library/react": "^12.1.2",
    "@testing-library/user-event": "^13.5.0",
    "arweave": "^1.10.23",
    "daisyui": "^1.22.0",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-scripts": "5.0.0",
    "weave-aggregator": "^0.1.2",
    "web-vitals": "^2.1.3"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "autoprefixer": "^10.4.2",
    "postcss": "^8.4.5",
    "tailwindcss": "^3.0.13"
  }
}

```
Maybe it is a webpack issue?

**Comment by charmful0x** [comment]
Hello @fewwwww !
I have just merged the other PR related to `permacast/api.js`  import issue. Could you please test again to see if the issue persists?

However, if you were only interested in permacast API, I suggest checking this repo https://github.com/Parallel-news/permacast-cache

**Comment by fewwwww** [comment]
Hi @charmful0x,

It is working perfectly with nodejs, but still getting the error when running it in React project. Maybe it is an arweave-js issue related to webpack, according to [this issue](https://github.com/ArweaveTeam/arweave-js/issues/67). 

We may rely on arweave-js team to solve this I think. I will try my best to see if I can work this out. I will try to use permacast-cache for now, but I will be thrilled if weave-aggregator can be directly ran in client-side React. It is a really powerful and easy-to-use library for Arweave feeds.

Thanks for the support!

**Comment by fewwwww** [comment]
Hi @charmful0x,
Finally 🥲 make it work by simply just add `default` between Arweave and init in `utils/arweave/arweave.js`
```js
export const arweave = Arweave.default.init({
  host: "arweave.net",
  port: 443,
  protocol: "https",
  timeout: 20000,
  logging: false,
});
``` 
I believe it is a weird behavior of React and it's not arweave-js's fault. 
The extra `default` only works for React, and for node, it will not work.
I add some notes in the README to specify that in the latest pr. 😀

**Comment by charmful0x** [comment]
Oh awesome, glad for this! Thank you for your support 🙌❤️
